apiVersion: v1
kind: Service
metadata:
  name: postgres-np
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
    - port: 5432
      nodePort: 30100
  selector:
    app: postgres

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres-clusterip
spec:
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: postgres